/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exam` | `/exam`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `/exam/attempt`; params?: Router.UnknownInputParams; } | { pathname: `/act/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/exam/result/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/image/[name]`, params: Router.UnknownInputParams & { name: string | number; } } | { pathname: `/learn/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/practice/[mode]/[sets]`, params: Router.UnknownInputParams & { mode: string | number;sets: string | number; } } | { pathname: `/questions/[mode]/[sets]`, params: Router.UnknownInputParams & { mode: string | number;sets: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/search`; params?: Router.UnknownOutputParams; } | { pathname: `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/exam` | `/exam`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownOutputParams; } | { pathname: `/exam/attempt`; params?: Router.UnknownOutputParams; } | { pathname: `/act/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/exam/result/[id]`, params: Router.UnknownOutputParams & { id: string; } } | { pathname: `/image/[name]`, params: Router.UnknownOutputParams & { name: string; } } | { pathname: `/learn/[slug]`, params: Router.UnknownOutputParams & { slug: string; } } | { pathname: `/practice/[mode]/[sets]`, params: Router.UnknownOutputParams & { mode: string;sets: string; } } | { pathname: `/questions/[mode]/[sets]`, params: Router.UnknownOutputParams & { mode: string;sets: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/search${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/exam${`?${string}` | `#${string}` | ''}` | `/exam${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/practice${`?${string}` | `#${string}` | ''}` | `/practice${`?${string}` | `#${string}` | ''}` | `/exam/attempt${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/search`; params?: Router.UnknownInputParams; } | { pathname: `/settings`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/exam` | `/exam`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/practice` | `/practice`; params?: Router.UnknownInputParams; } | { pathname: `/exam/attempt`; params?: Router.UnknownInputParams; } | `/act/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/exam/result/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/image/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/learn/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/practice/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | `/questions/${Router.SingleRoutePart<T>}/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/act/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/exam/result/[id]`, params: Router.UnknownInputParams & { id: string | number; } } | { pathname: `/image/[name]`, params: Router.UnknownInputParams & { name: string | number; } } | { pathname: `/learn/[slug]`, params: Router.UnknownInputParams & { slug: string | number; } } | { pathname: `/practice/[mode]/[sets]`, params: Router.UnknownInputParams & { mode: string | number;sets: string | number; } } | { pathname: `/questions/[mode]/[sets]`, params: Router.UnknownInputParams & { mode: string | number;sets: string | number; } };
    }
  }
}
